# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'medical-app' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for medical-app

  pod ‘Firebase’
  pod ‘Firebase/Auth’
  pod ‘Firebase/Database’
  pod ‘GoogleSignIn’
  pod ‘FBSDKLoginKit’
  pod ‘Fabric’
  pod ’TwitterKit’
  pod 'Firebase/Storage'


end
